version: "3.8"
services:
  main-page:
    build: ./main-page
    container_name: front_container
    ports: 
      - '3000:3000'
    stdin_open: true
    tty: true    
  ms-create:
    build: ./MS-Create
    container_name: service_create
    ports: 
      - '8002:8002'
