version: "3.8"

services:
  main-page:
    build: ./main-page
    container_name: front_container
    ports: 
      - '3000:3000'
    stdin_open: true
    tty: true

  ms-create:
    build: ./MS-Create
    container_name: service_create
    ports:
      - '8002:8002'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./MS-Create:/app
  
  ms-delete:
    build: ./MS-Delete
    container_name: service_delete
    ports:
      - '8001:8001'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./MS-Delete:/app

  ms-log:
    build: ./MS-Log
    container_name: service_log
    ports:
      - '8004:8004'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./MS-Log:/app

  ms-read:
    build: ./MS-Read
    container_name: service_read
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./MS-Read:/app

  ms-update:
    build: ./MS-Update
    container_name: service_update
    ports:
      - '8003:8003'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./MS-Update:/app
      
  db:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PW}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Monta el script en la carpeta de inicialización
